name             'jenkins_app_server'
maintainer       'Vince Montalbano'
maintainer_email 'vince.montalbano@gmail.com'
license          'All rights reserved'
description      'Installs/Configures Jenkins'
long_description 'Installs/Configures Jenkins'
version          '0.1.0'

depends 'devops_base', '>= 0.1.0'
depends 'jenkins'
